# Generated by Django 3.0.7 on 2020-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200614_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(choices=[('카드발급', '카드발급'), ('카드분실', '카드분실'), ('카드재발급', '카드재발급')], max_length=60),
        ),
    ]
