# Generated by Django 3.0.7 on 2020-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(choices=[('카드발급', 'a'), ('카드분실', 'b'), ('카드재발', 'c')], max_length=60),
        ),
    ]
