# Generated by Django 3.0.6 on 2020-05-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '패스트캠퍼스 게시글', 'verbose_name_plural': '패스트캠퍼스 게시글'},
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='태그'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='fastcampus_board',
        ),
    ]
