# Generated by Django 3.0.6 on 2020-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200506_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '언어 리스트', 'verbose_name_plural': '언어 리스트'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default=1, max_length=130, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
